### ISSUE TITLE
Any way we can improve the gradient on groups?

### ISSUE THREAD

**Issue by starkers** [dracula/hyprland#5]
Lovely dracula colours thanks.. just wondering if anyone has and ideas how to improve window groups?

The gradient just feels bad and hard to read.. see screenshot

![image](https://github.com/dracula/hyprland/assets/462087/41dc1b54-dc90-4a65-9803-e213e11f6b8c)

**Comment by Keloran** [comment]
Is this any better https://github.com/dracula/hyprland/tree/gradientOnGroupBars ?

I don't really use groups, so never noticed it sorry
